
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.67.143.149:3306/swith?useSSL=false&characterEncoding=utf8&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: swith
  jpa:
#    show-sql: true
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "dhtkdals0528@gmail.com"
    password: "MIN970528!"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
