
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swith?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: min970528!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "dhtkdals0528@gmail.com"
    password: "MIN970528!"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    encoding:
      charset: UTF-8
